export const recommendationOptions = [
  { id: 'tourist', text: 'Top Tourist Attractions' },
  { id: 'cities', text: 'Best cities to visit' },
  { id: 'michelin', text: 'Michelin Guide Restaurants' },
  { id: 'budget', text: 'Top 10 Budget Tips' },
{ id: 'adventure', text: 'Adventure Activities' },
{ id: 'food', text: 'Food/Beverage Ideas' },
{ id: 'culture', text: 'Cultural Experiences' },
{ id: 'nightlife', text: 'Nightlife and Entertainment' },
{ id: 'nature', text: 'Nature and Outdoor Activities' },
{ id: 'shopping', text: 'Shopping Destinations' }
];
// export const recommendationOptions = [
//   { id: 'tourist', text: 'Tourist Attractions' },
//   { id: 'food', text: 'Food/Beverage Ideas' },
//   { id: 'adventure', text: 'Adventure Activities' },
//   { id: 'budget', text: 'Budget Friendly Options' }
// ];

export const COUNTRY_BLACKLIST = [
  'ATA', // Antarctica
  'GRL', // Greenland
  'HMD', // Heard Island and McDonald Islands
  'WLF', // Wallis and Futuna
  'ESH', // Western Sahara
  'TKL', // Tokelau
  'UMI', // United States Minor Outlying Islands
  'VGB', // British Virgin Islands
  'VIR', // United States Virgin Islands
  'CXR', // Christmas Island
  'CCK', // Cocos (Keeling) Islands
  'NFK', // Norfolk Island
  'ATF', // French Southern and Antarctic Lands
];

export const COUNTRY_COLORS = {
  BLACKLIST: '#7a848d', // Lighter blue for blacklisted countries
  WHITELIST: '#4a90e2' // Default color for other countries
};

export const TRAVEL_TOPICS = [
  'Travel Hacks',
  'Cultural Experiences',
  'Adventure Travel',
  'Hotels and Accommodations',
  'Food and Cuisine',
  'Top 10 Lists',
  'Airbnb and Vacation Rentals',
  'Nightlife',
  'Nature and Outdoor Activities',
  'Shopping',
  'Budget Travel',
  'Luxury Travel',
  'Travel Photography',
  'Travel Safety',
  'Travel Tips',
  'Travel Guides',
  'Travel Destinations',
  'Travel Stories',
  'Travel Gear',
  'Travel Apps',
  'Travel Insurance',
  'Travel Health',
  'Travel Etiquette',
  'Travel Planning',
  'Travel Inspiration',
  'Travel Trends',
  'Travel Technology',
  'Travel Sustainability',
  'Travel Communities',
  'Travel Blogs',
  'Travel Vlogs',
  'Travel Podcasts',
  'Travel Books',
  'Travel Events',
  'Travel Contests',
  'Travel Photography Tips',
  'Travel Writing',
  'Travel Language Tips',
  'Travel History',
  'Museums and Galleries',
  'Wildlife and Nature',
  'Beaches and Islands',
  'Road Trips',
  'City Guides',
  'Traveling with Kids',
  'Solo Travel',
  'Group Travel',
  'Business Travel'
];

export const COUNTRY_LIST = [
  { name: 'United States', countryCode: 'USA' },
  { name: 'Canada', countryCode: 'CAN' },
  { name: 'Mexico', countryCode: 'MEX' },
  { name: 'United Kingdom', countryCode: 'GBR' },
  { name: 'France', countryCode: 'FRA' },
  { name: 'Germany', countryCode: 'DEU' },
  { name: 'Italy', countryCode: 'ITA' },
  { name: 'Spain', countryCode: 'ESP' },
  { name: 'Australia', countryCode: 'AUS' },
  { name: 'Japan', countryCode: 'JPN' },
  { name: 'South Korea', countryCode: 'KOR' },
  { name: 'China', countryCode: 'CHN' },
  { name: 'India', countryCode: 'IND' },
  { name: 'Brazil', countryCode: 'BRA' },
  { name: 'Argentina', countryCode: 'ARG' },
  { name: 'South Africa', countryCode: 'ZAF' },
  { name: 'Russia', countryCode: 'RUS' },
  { name: 'Turkey', countryCode: 'TUR' },
  { name: 'Egypt', countryCode: 'EGY' },
  { name: 'Indonesia', countryCode: 'IDN' },
  { name: 'Malaysia', countryCode: 'MYS' },
  { name: 'Singapore', countryCode: 'SGP' },
  { name: 'Philippines', countryCode: 'PHL' },
  { name: 'New Zealand', countryCode: 'NZL' },
  { name: 'Sweden', countryCode: 'SWE' },
  { name: 'Norway', countryCode: 'NOR' },
  { name: 'Finland', countryCode: 'FIN' },
  { name: 'Denmark', countryCode: 'DNK' },
  { name: 'Netherlands', countryCode: 'NLD' },
  { name: 'Belgium', countryCode: 'BEL' },
  { name: 'Switzerland', countryCode: 'CHE' },
  { name: 'Austria', countryCode: 'AUT' },
  { name: 'Poland', countryCode: 'POL' },
  { name: 'Czech Republic', countryCode: 'CZE' },
  { name: 'Hungary', countryCode: 'HUN' },
  { name: 'Portugal', countryCode: 'PRT' },
  { name: 'Greece', countryCode: 'GRC' },
  { name: 'Ireland', countryCode: 'IRL' },
  { name: 'Iceland', countryCode: 'ISL' },
  { name: 'Croatia', countryCode: 'HRV' },
  { name: 'Slovenia', countryCode: 'SVN' },
  { name: 'Serbia', countryCode: 'SRB' },
  { name: 'Bulgaria', countryCode: 'BGR' },
  { name: 'Romania', countryCode: 'ROU' },
  { name: 'Ukraine', countryCode: 'UKR' },
  { name: 'Belarus', countryCode: 'BLR' },
  { name: 'Lithuania', countryCode: 'LTU' },
  { name: 'Latvia', countryCode: 'LVA' },
  { name: 'Estonia', countryCode: 'EST' },
  { name: 'Slovakia', countryCode: 'SVK' },
  { name: 'Luxembourg', countryCode: 'LUX' },
  { name: 'Malta', countryCode: 'MLT' },
  { name: 'Cyprus', countryCode: 'CYP' },
  { name: 'Andorra', countryCode: 'AND' },
  { name: 'Monaco', countryCode: 'MCO' },
  { name: 'Liechtenstein', countryCode: 'LIE' },
  { name: 'San Marino', countryCode: 'SMR' },
  { name: 'Vatican City', countryCode: 'VAT' },
  { name: 'Albania', countryCode: 'ALB' },
  { name: 'Bosnia and Herzegovina', countryCode: 'BIH' },
  { name: 'North Macedonia', countryCode: 'MKD' },
  { name: 'Moldova', countryCode: 'MDA' },
  { name: 'Armenia', countryCode: 'ARM' },
  { name: 'Azerbaijan', countryCode: 'AZE' },
  { name: 'Georgia', countryCode: 'GEO' },
  { name: 'Uzbekistan', countryCode: 'UZB' },
  { name: 'Kyrgyzstan', countryCode: 'KGZ' },
  { name: 'Tajikistan', countryCode: 'TJK' },
  { name: 'Iran', countryCode: 'IRN' },
  { name: 'Syria', countryCode: 'SYR' },
  { name: 'Lebanon', countryCode: 'LBN' },
  { name: 'Jordan', countryCode: 'JOR' },
  { name: 'Iraq', countryCode: 'IRQ' },
  { name: 'Saudi Arabia', countryCode: 'SAU' },
  { name: 'United Arab Emirates', countryCode: 'ARE' },
  { name: 'Qatar', countryCode: 'QAT' },
  { name: 'Kuwait', countryCode: 'KWT' },
  { name: 'Oman', countryCode: 'OMN' },
  { name: 'Bahrain', countryCode: 'BHR' },
  { name: 'Yemen', countryCode: 'YEM' },
  { name: 'Afghanistan', countryCode: 'AFG' },
  { name: 'Pakistan', countryCode: 'PAK' },
  { name: 'Bangladesh', countryCode: 'BGD' },
  { name: 'Sri Lanka', countryCode: 'LKA' },
  { name: 'Nepal', countryCode: 'NPL' },
  { name: 'Bhutan', countryCode: 'BTN' },
  { name: 'Maldives', countryCode: 'MDV' },
  { name: 'Myanmar', countryCode: 'MMR' },
  { name: 'Laos', countryCode: 'LAO' },
  { name: 'Brunei', countryCode: 'BRN' },
  { name: 'Mongolia', countryCode: 'MNG' },
  { name: 'Kazakhstan', countryCode: 'KAZ' },
  { name: 'Turkmenistan', countryCode: 'TKM' },
  { name: 'Vietnam', countryCode: 'VNM' },
  { name: 'Thailand', countryCode: 'THA' },
  { name: 'Cambodia', countryCode: 'KHM' },
  { name: 'Timor-Leste', countryCode: 'TLS' },
  { name: 'Fiji', countryCode: 'FJI' },
  { name: 'Papua New Guinea', countryCode: 'PNG' },
  { name: 'Solomon Islands', countryCode: 'SLB' },
  { name: 'Vanuatu', countryCode: 'VUT' },
  { name: 'Samoa', countryCode: 'WSM' },
  { name: 'Tonga', countryCode: 'TON' },
  { name: 'Kiribati', countryCode: 'KIR' },
  { name: 'Tuvalu', countryCode: 'TUV' },
  { name: 'Nauru', countryCode: 'NRU' },
  { name: 'Marshall Islands', countryCode: 'MHL' },
  { name: 'Palau', countryCode: 'PLW' },
  { name: 'Micronesia', countryCode: 'FSM' },
  { name: 'Northern Mariana Islands', countryCode: 'MNP' },
  { name: 'Guam', countryCode: 'GUM' },
  { name: 'American Samoa', countryCode: 'ASM' },
  { name: 'Cook Islands', countryCode: 'COK' },
  { name: 'Niue', countryCode: 'NIU' },
  { name: 'Tokelau', countryCode: 'TKL' },
  { name: 'Wallis and Futuna', countryCode: 'WLF' },
  { name: 'French Polynesia', countryCode: 'PYF' },
  { name: 'New Caledonia', countryCode: 'NCL' },
  { name: 'Saint Pierre and Miquelon', countryCode: 'SPM' },
  { name: 'Montserrat', countryCode: 'MSR' },
  { name: 'Bermuda', countryCode: 'BMU' },
  { name: 'Cayman Islands', countryCode: 'CYM' },
  { name: 'Turks and Caicos Islands', countryCode: 'TCA' },
  { name: 'Anguilla', countryCode: 'AIA' },
  { name: 'British Virgin Islands', countryCode: 'VGB' },
  { name: 'United States Virgin Islands', countryCode: 'VIR' },
  { name: 'Saint Kitts and Nevis', countryCode: 'KNA' },
  { name: 'Antigua and Barbuda', countryCode: 'ATG' },
  { name: 'Dominica', countryCode: 'DMA' },
  { name: 'Saint Lucia', countryCode: 'LCA' },
  { name: 'Saint Vincent and the Grenadines', countryCode: 'VCT' },
  { name: 'Barbados', countryCode: 'BRB' },
  { name: 'Grenada', countryCode: 'GRD' },
  { name: 'Trinidad and Tobago', countryCode: 'TTO' },
  { name: 'Bahamas', countryCode: 'BHS' },
  { name: 'Jamaica', countryCode: 'JAM' },
  { name: 'Haiti', countryCode: 'HTI' },
  { name: 'Dominican Republic', countryCode: 'DOM' },
  { name: 'Cuba', countryCode: 'CUB' },
  { name: 'Puerto Rico', countryCode: 'PRI' },
  { name: 'Aruba', countryCode: 'ABW' },
  { name: 'Curacao', countryCode: 'CUW' },
  { name: 'Sint Maarten', countryCode: 'SXM' },
  { name: 'Bonaire', countryCode: 'BES' },
  { name: 'Saba', countryCode: 'SAB' },
  { name: 'Sint Eustatius', countryCode: 'EUZ' },
  { name: 'Greenland', countryCode: 'GRL' },
  { name: 'Faroe Islands', countryCode: 'FRO' },
  { name: 'Morocco', countryCode: 'MAR' },
  { name: 'Algeria', countryCode: 'DZA' },
  { name: 'Tunisia', countryCode: 'TUN' },
  { name: 'Libya', countryCode: 'LBY' },
  { name: 'Niger', countryCode: 'NER' },
  { name: 'Chad', countryCode: 'TCD' },
  { name: 'Sudan', countryCode: 'SDN' },
  { name: 'South Sudan', countryCode: 'SSD' },
  { name: 'Eritrea', countryCode: 'ERI' },
  { name: 'Djibouti', countryCode: 'DJI' },
  { name: 'Somalia', countryCode: 'SOM' },
  { name: 'Ethiopia', countryCode: 'ETH' },
  { name: 'Kenya', countryCode: 'KEN' },
  { name: 'Uganda', countryCode: 'UGA' },
  { name: 'Rwanda', countryCode: 'RWA' },
  { name: 'Burundi', countryCode: 'BDI' },
  { name: 'Tanzania', countryCode: 'TZA' },
  { name: 'Mozambique', countryCode: 'MOZ' },
  { name: 'Zambia', countryCode: 'ZMB' },
  { name: 'Zimbabwe', countryCode: 'ZWE' },
  { name: 'Namibia', countryCode: 'NAM' },
  { name: 'Botswana', countryCode: 'BWA' },
  { name: 'Lesotho', countryCode: 'LSO' },
  { name: 'Eswatini', countryCode: 'SWZ' },
  { name: 'Seychelles', countryCode: 'SYC' },
  { name: 'Madagascar', countryCode: 'MDG' },
  { name: 'Comoros', countryCode: 'COM' },
  { name: 'Mauritius', countryCode: 'MUS' },
  { name: 'Reunion', countryCode: 'REU' },
  { name: 'Cape Verde', countryCode: 'CPV' },
  { name: 'Ghana', countryCode: 'GHA' },
  { name: 'Nigeria', countryCode: 'NGA' },
  { name: 'Benin', countryCode: 'BEN' },
  { name: 'Togo', countryCode: 'TGO' },
  { name: 'Burkina Faso', countryCode: 'BFA' },
  { name: 'Cote d\'Ivoire', countryCode: 'CIV' },
  { name: 'Liberia', countryCode: 'LBR' },
  { name: 'Sierra Leone', countryCode: 'SLE' },
  { name: 'Guinea', countryCode: 'GIN' },
  { name: 'Guinea-Bissau', countryCode: 'GNB' },
  { name: 'Senegal', countryCode: 'SEN' },
  { name: 'The Gambia', countryCode: 'GMB' },
  { name: 'Mali', countryCode: 'MLI' },
  { name: 'Mauritania', countryCode: 'MRT' },
  { name: 'Central African Republic', countryCode: 'CAF' },
  { name: 'Cameroon', countryCode: 'CMR' },
  { name: 'Gabon', countryCode: 'GAB' },
  { name: 'Democratic Republic of the Congo', countryCode: 'COD' },
  { name: 'Equatorial Guinea', countryCode: 'GNQ' },
  { name: 'Angola', countryCode: 'AGO' },
  { name: 'Sao Tome and Principe', countryCode: 'STP' },
  { name: 'Israel', countryCode: 'ISR' },
  { name: 'Palestine', countryCode: 'PSE' },
].sort((a, b) => a.name.localeCompare(b.name));
